### ISSUE TITLE
cocoapods集成后问题太多了!!!!赶紧过来看.

### ISSUE THREAD

**Issue by gongxiaokai** [easemob/easeui-ios-hyphenate-cocoapods#13]
1.少c++编译库
2.使用Lite版本头文件全部报错 (当然可以手动一个一个改)
3.EaseUI.h 头文件引入报错虽然加了TARGET_OS_IPHONE的判断 但还是走到else中然而cocoapods管理的Ease文件并没有UIImageView+WebCache UIViewController+HUD 等等文件.最严重的是这个头文件是无法修改.
总结:无法使用cocoapods集成easeUI.希望官方能解决.

**Comment by lizilong1989** [comment]
@gongxiaokai 
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.2.2'
可以使用3.2.2这个版本

**Comment by lizilong1989** [comment]
@gongxiaokai 感谢反馈,EaseUI会尽快修复这些问题

**Comment by lizilong1989** [comment]
@gongxiaokai 针对集成Lite版本SDK和EaseUI已经做了优化，readme中有特殊说明，针对Lite版本SDK使用：
pod 'EaseUILite', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
