### ISSUE TITLE
混合swift编译失败

### ISSUE THREAD

**Issue by mllw** [easemob/easeui-ios-hyphenate-cocoapods#18]
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/EaseUI-umbrella.h"
        ^
/Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/EaseUI-umbrella.h:25:9: note: in file included from /Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/EaseUI-umbrella.h:25:
_#import "wav.h"
        ^_
/Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/wav.h:24:1: error: unknown type name 'class'; did you mean 'Class'?
class WavWriter {
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/objc/objc.h:38:28: note: 'Class' declared here
typedef struct objc_class *Class;
                           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/EaseUI-umbrella.h"
        ^
/Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/EaseUI-umbrella.h:25:9: note: in file included from /Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/EaseUI-umbrella.h:25:
#import "wav.h"
        ^
/Users/mllw/Library/Developer/Xcode/DerivedData/VHSIPro-cbzywzzpqnzuigdfrtadqljjhgtr/Build/Products/Debug-iphoneos/EaseUI/EaseUI.framework/Headers/wav.h:24:16: error: expected ';' after top level declarator
class WavWriter {
               ^
/Volumes/skd/workspace/iOS/objc/VHSIPro/VHSIPro/swift/VHAppDelegate.swift:12:8: error: could not build Objective-C module 'EaseUI'
import EaseUI
       ^

**Comment by lizilong1989** [comment]
@mllw 此问题已经修复，pod update，重新下载EaseUI
