### ISSUE TITLE
请尽快升级你们使用的第三方库

### ISSUE THREAD

**Issue by syq7970** [easemob/easeui-ios-hyphenate-cocoapods#20]
比如MBProgressHUD 我们使用的已经是1.0以上版本了，而你们还是用的0.9.2的版本，这样在集成的时候会造成冲突。

**Comment by lizilong1989** [comment]
@syq7970 MBProgressHUD这个是通过MWPhotoBrowser引入进来的，目前最新MWPhotoBrowser依赖的MBProgressHUD让然是0.9。

**Comment by lizilong1989** [comment]
@syq7970 MBProgressHUD你是使用pod导入的吗？如果是的话，pod install只会下载一份，不会重复下载导致冲突

**Comment by lizilong1989** [comment]
@syq7970  EaseUI升级版本没有用，这个是MWPhotoBrowser的问题，目前能做的就是不用MWPhotoBrowser。我们也会尽快解决此问题

**Comment by lizilong1989** [comment]
@syq7970 你也可以在Podfile中，添加：
pod 'MWPhotoBrowser', :git => 'https://github.com/lizilong1989/MWPhotoBrowser.git'
这是我fork了一份MWPhotoBrowser，并且将MBProgressHUD指定版本为1.0.0
我本地测试没发现问题，你也可以测试一下
