### ISSUE TITLE
- `Hyphenate (~> 3.3.2)` required by `EaseUI (3.3.2)`

### ISSUE THREAD

**Issue by liaogang** [easemob/easeui-ios-hyphenate-cocoapods#26]

**Comment by lizilong1989** [comment]
@liaogang 现在EaseUI直接依赖了Hyphenate，是不是项目依赖SDK的版本过低？可以指定依赖EaseUI的版本与SDK相同

pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.x.x'
