### ISSUE TITLE
 自动打包失败

### ISSUE THREAD

**Issue by Jiuaim** [easemob/easeui-ios-hyphenate-cocoapods#28]
error: Resource "/Users/geping/Library/Developer/Xcode/DerivedData/boyibang-cwasfhgldmuxkdeuwchmmobouiho/Build/Products/Debug-iphoneos/MWPhotoBrowser/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.

工程在自动打包过程中pod管理的EaseUI依赖的第三方MWPhotoBrowser,iphoneos模式下不存在MWPhotoBrowser.bundle,导致打包失败,Debug-iphonesimulator没问题

**Comment by lizilong1989** [comment]
@Jiuaim 如果已经通过pod集成了easeui，MWPhotoBrowser.bundle会自动下载至本地，需要验证一下xcode是否能打包成功，如果可以再看看是不是打包脚本的问题

**Comment by Jiuaim** [comment]
您好:在真机上清空了DrivedData后依然是能够打包成功的,脚本中会执行一次xcodebuild clean -workspace $workspace_name.xcworkspace -scheme "$scheme" -configuration "$configuration",如果不执行行命令,自己手动在给MWPhotoBrowser编译生成文件是能够打包成功的.是不是你们那边没有编译这个第三方呢?

**Comment by lizilong1989** [comment]
@Jiuaim 刚才我测试了一下，build是正常的，iphoneos没问题，这是我测试的命令
 xcodebuild -workspace EaseMobLiveDemo.xcworkspace -scheme EaseMobLiveDemo -configuration Release -sdk iphoneos clean build
我认为xcode可以build通过，脚本应该就不会有问题
