### ISSUE TITLE
MBProgressHUD版本问题

### ISSUE THREAD

**Issue by CaiChenghan** [easemob/easeui-ios-hyphenate-cocoapods#35]
MBProgressHUD的版本都到1.0.0了，你们怎么还在用0.9.2的，能更新一下吗？

**Comment by wehuazi** [comment]
现在版本都1.1.0了，强烈建议更新一下！

**Comment by designfuchen** [comment]
MBProgressHUD的版本都到1.0.0了能不能更新啊

**Comment by designfuchen** [comment]
1.1.0了

**Comment by nilhy** [comment]
强烈建议 MBProgressHUD 升级1.1.0 , 项目中有好多依赖,然后easyUI 要0.9
