### ISSUE TITLE
中英文 Localizable.strings显示为乱码

### ISSUE THREAD

**Issue by dearbar** [easemob/easeui-ios-hyphenate-cocoapods#37]
中英文 Localizable.strings显示为乱码

**Comment by lizilong1989** [comment]
@dearbar 这个不会影app显示

**Comment by dearbar** [comment]
谢谢你的回复，但我在iPhone5测试时遇到的些问题。我手机设置为中文，但是app内显示为英文。明天如果有时间我会把具体的问题提交给你。😀

2017-09-27 11:44 GMT+08:00 李子龙 <notifications@github.com>:
