### ISSUE TITLE
EaseUI 为什么不加版本来控制一下呢?

### ISSUE THREAD

**Issue by jason469618528** [easemob/easeui-ios-hyphenate-cocoapods#6]
UP

**Comment by lizilong1989** [comment]
@jason469618528 由于easeui没有push到cocoapods上,可以通过指定tag,使用不同版本的easeui

**Comment by lizilong1989** [comment]
@jason469618528 pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.2.2' 可以这样指定版本

**Comment by jason469618528** [comment]
@lizilong1989 好的，谢谢。我想问一下，你这个库是官方认可的吗?

**Comment by lizilong1989** [comment]
@jason469618528 是认可的,官网上有集成文档http://docs.easemob.com/im/300iosclientintegration/85easeuiguide
