### ISSUE TITLE
pod falied

### ISSUE THREAD

**Issue by chocolatemetoprolol** [easemob/easeui-ios-hyphenate-cocoapods#9]
#import <EaseUI/UIImageView+WebCache.h> file not found

**Comment by chocolatemetoprolol** [comment]
Pods/Headers/Public/EaseUI/EaseUI.h:69:9: 'EaseUI/UIImageView+WebCache.h' file not found

**Comment by lizilong1989** [comment]
@chocolatemetoprolol #import <SDWebImage/UIImageView+WebCache.h>
"UIImageView+WebCache.h"是通过dependency引入进来的(spec.dependency 'MWPhotoBrowser', '~> 2.1.1')

**Comment by lizilong1989** [comment]
@chocolatemetoprolol EaseUI will fix soon

**Comment by lizilong1989** [comment]
@chocolatemetoprolol 问题已经修复，请注意及时更新
